<%@LANGUAGE=VBSCRIPT%>
<%OPTION EXPLICIT%>
<!--#INCLUDE FILE="OurDatabaseConnect.ASP"-->
<html>
<body>
<%
DIM OBJRS,bola
IF((REQUEST.FORM("EMAIL")="") OR (REQUEST.FORM("PHONE")="") _
OR (REQUEST.FORM("ADDRESS")="")) THEN
RESPONSE.WRITE "<A HREF='PROFILE.asp'>"
RESPONSE.WRITE "YOU MUST ENTER VALUES FOR ALL THE FIELDS"
RESPONSE.WRITE "</A>"

ELSE

BOLA=FALSE
set OBJRS = server.createobject("adodb.recordset")
OBJRS.OPEN "registration",OBJCONN, ,adLockOptimistic,adCmdTable
IF NOT BOLA THEN
DO WHILE NOT (OBJRS.EOF)
IF session("un")=objrs("UNAME") THEN
OBJRS("EMAIL")=REQUEST.FORM("EMAIL")
OBJRS("PHONE")=REQUEST.FORM("PHONE")
OBJRS("ADDRESS")=REQUEST.FORM("ADDRESS")
OBJRS.UPDATE
RESPONSE.WRITE "UR PROFILE UPDATED"
response.write "<br> "
response.write "<br> "
response.write "THANK YOU "
ELSE
END IF
OBJRS.MOVENEXT
loop
END IF
OBJRS.CLOSE
SET OBJRS=NOTHING
END IF
OBJCONN.CLOSE
SET OBJCONN=NOTHING
%>
</BODY>
</HTML>
