<%@LANGUAGE=VBSCRIPT%>
<%OPTION EXPLICIT%>
<!--#INCLUDE FILE="OurDatabaseConnect.ASP"-->
<html>
<body>
<%
DIM OBJRS,bola
IF((REQUEST.FORM("SUBJECT")="") OR (REQUEST.FORM("DESCRIPTION")="")) THEN
RESPONSE.WRITE "<A HREF='FEEDBACK.asp'>"
RESPONSE.WRITE "YOU MUST ENTER VALUES FOR ALL THE FIELDS"
RESPONSE.WRITE "</A>"
ELSE
BOLA=FALSE
set OBJRS = server.createobject("adodb.recordset")
OBJRS.OPEN "FEEDBACK",OBJCONN, ,adLockOptimistic,adCmdTable
IF NOT BOLA THEN
OBJRS.ADDNEW
OBJRS("SUBJECT")=REQUEST.FORM("SUBJECT")
OBJRS("DESCRIPTION")=REQUEST.FORM("DESCRIPTION")
OBJRS("UNAME")=SESSION("UN")
OBJRS("DATEE")= DATE
OBJRS("DISTRICT")=SESSION("PN")
OBJRS("FNAME")=SESSION("BN")
OBJRS.UPDATE
RESPONSE.WRITE "<A HREF='consumer.asp'>"
RESPONSE.WRITE "THANK YOU FOR YOUR FEEDBACK"
RESPONSE.WRITE "</A>"
END IF
OBJRS.CLOSE
SET OBJRS=NOTHING
END IF
OBJCONN.CLOSE
SET OBJCONN=NOTHING
%>
</BODY>
</HTML>
