<%@LANGUAGE=VBSCRIPT%>
<%OPTION EXPLICIT%>
<!--#INCLUDE FILE="OurDatabaseConnect.ASP"-->
<%
DIM OBJRS,OBJRS1,OBJRS2
DIM TOTAL,COUNT
COUNT=0
SET OBJRS = server.createobject("adodb.recordset")
OBJRS.OPEN "DISTSTOCK",OBJCONN, ,adLockOptimistic,adCmdTable
DO WHILE NOT OBJRS.EOF
	IF(STRCOMP(OBJRS("DISTRICT"),SESSION ("UN"),VBTEXTCOMPARE)=0) THEN
	TOTAL= OBJRS("STOCK")
	END IF
OBJRS.MOVENEXT
LOOP

OBJRS.CLOSE
SET OBJRS=NOTHING 
SET OBJRS1 = server.createobject("adodb.recordset")
OBJRS1.OPEN "BOOKING",OBJCONN, ,adLockOptimistic,adCmdTable

DO WHILE NOT OBJRS1.EOF
IF(STRCOMP(OBJRS1("DISTRICT"),SESSION ("UN"),VBTEXTCOMPARE)=0) THEN
	IF ((TOTAL>0) AND OBJRS1("STATUS")="PENDING") THEN
	OBJRS1("STATUS")="DELIVERED"
	TOTAL=TOTAL-1
	COUNT=COUNT+1
	OBJRS1.UPDATE
	END IF
END IF
	
OBJRS1.MOVENEXT
LOOP

OBJRS1.CLOSE
SET OBJRS1=NOTHING

set OBJRS2 = server.createobject("adodb.recordset")
OBJRS2.OPEN "DISTSTOCK",OBJCONN, ,adLockOptimistic,adCmdTable
DO WHILE NOT OBJRS2.EOF
	IF(STRCOMP(OBJRS2("DISTRICT"),SESSION ("UN"),VBTEXTCOMPARE)=0) THEN
	OBJRS2("STOCK")=TOTAL
	OBJRS2("COUNT")=OBJRS2("COUNT")+COUNT
	OBJRS2.UPDATE
	END IF
OBJRS2.MOVENEXT
LOOP
RESPONSE.WRITE "<A HREF='REQUEST.asp'>"
RESPONSE.WRITE "Dispatch Successful"
RESPONSE.WRITE "</A>"

OBJRS2.CLOSE
SET OBJRS2=NOTHING

OBJCONN.CLOSE
SET OBJCONN=NOTHING
%>

