<%@LANGUAGE=VBSCRIPT%>
<%OPTION EXPLICIT%>
<!--#INCLUDE FILE="DATABASECONNECT.ASP"-->
<HTML>
<BODY>
<%
DIM OBJRS,BOLA
IF((REQUEST.FORM("UN")="") OR (REQUEST.FORM("PW")="") _
OR (REQUEST.FORM("EMAIL")="") OR (REQUEST.FORM("FN")="") _
OR (REQUEST.FORM("LN")="")) THEN
RESPONSE.WRITE "<A HREF='REG1.HTML'>"
RESPONSE.WRITE "YOU MUST ENTER VALUES FOR ALL THE FIELDS"
RESPONSE.WRITE "</A>"
ELSE
BOLA=FALSE
set OBJRS = server.createobject("adodb.recordset")
OBJRS.OPEN "USER",OBJCONN, ,adLockOptimistic,adCmdTable
%>
<B>ENTRIES IN TABLE</B>
<P>
<TABLE BORDER=5>
<TR>
<TD>NAME</TD>
<TD>EMIAL</TD>
<TD>USERNAME</TD>
</TR>
<%
DO WHILE NOT OBJRS.EOF%>
<TR>
<TD><%=OBJRS("LASTNAME")%>,<%=OBJRS("FIRSTNAME")%></TD>
<TD><%=OBJRS("EMAIL")%></TD>
<TD><%=OBJRS("USERNAME")%></TD>
</TR>
<%
OBJRS.MOVENEXT
LOOP
OBJRS.MOVEFIRST
DO WHILE NOT (OBJRS.EOF OR BOLA)
IF(STRCOMP(OBJRS("USERNAME"),REQUEST.FORM("UN"),VBTEXTCOMPARE)=0) THEN
RESPONSE.WRITE "<A HREF='REG1.HTML'>"
RESPONSE.WRITE "<USER NAME ALREADY EXISTS."
RESPONSE.WRITE"</A>"
BOLA=TRUE
END IF
IF(STRCOMP(OBJRS("EMAIL"),REQUEST.FORM("EMAIL"),VBTEXTCOMPARE)=0) THEN
RESPONSE.WRITE "<A HREF='REG1.HTML'>"
RESPONSE.WRITE "EMAIL ALREADY EXISTS."
RESPONSE.WRITE"</A>"
BOLA=TRUE
END IF
OBJRS.MOVENEXT
LOOP
IF NOT BOLA THEN
OBJRS.MOVEFIRST
OBJRS("FIRSTNAME")=REQUEST.FORM("FN")
OBJRS("LASTNAME")=REQUEST.FORM("LN")
OBJRS("EMAIL")=REQUEST.FORM("EMAIL")
OBJRS("USERNAME")=REQUEST.FORM("UN")
OBJRS("PASSWORD")=REQUEST.FORM("PW")
OBJRS.UPDATE
OBJRS.MOVEFIRST
END IF
%>
</TABLE>
<% 
RESPONSE.WRITE "UPDATION PERFOMED SUCCESSFULLY"%>
<BR><B>AFTER MODIFICATION DATA IS</B>
<BR>
<P>
<TABLE BORDER=5>
<TR>
<TD>NAME</TD>
<TD>EMIAL</TD>
<TD>USERNAME</TD>
</TR>
<%
DO WHILE NOT OBJRS.EOF %>
<TR>
<TD><%=OBJRS("LASTNAME")%>,<%=OBJRS("FIRSTNAME")%></TD>
<TD><%=OBJRS("EMAIL")%></TD>
<TD><%=OBJRS("USERNAME")%></TD>
</TR>
<%
OBJRS.MOVENEXT
LOOP
%>
</TABLE>
<%
OBJRS.CLOSE
SET OBJRS=NOTHING
END IF
OBJCONN.CLOSE
SET OBJCONN=NOTHING
%>
</BODY>
</HTML>
